
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - relationships:
              to: ref('my_first_dbt_model')
              field: id
  - name: playing_with_tests
    description: "Udemy test assignment"
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null

      - name: c_mktsegment
        tests:
          - accepted_values:
              values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']

  # - name: snowflake_customer_purchases
  #   description: "Total purchases for each cstomer in snowflake sample data"
  #   columns:
  #     - name: c_custkey
  #       description: "The primary key for customer table"
  #       tests:
  #       - unique
  #       - not_null

  # - name: cumulative_orders_by_date
  #   description: "sum of order price by date"
  #   columns:
  #     - name: o_orderdate
  #       description: "date of purchase"
  #       tests:
  #       - unique
  #       - not_null

  # - name: times

sources:
  - name: sample
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders